collections:
  pages:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: "fred belotte"
      layout: post
  - scope:
      path: ""
    values:
      layout: base

plugins:
  - jekyll-sitemap

title: DERFTX
