jobs:
  build:
    name: build
    uses: fredbelotte/fredbelotte/.github/workflows/build.yaml@main
    with:
      jekyll_destination: _site
      jekyll_source: jekyll

  scan_dotnet:
    name: scan_dotnet
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: configure
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: install
        run: dotnet tool install --global dotnet-sonarscanner
      - name: scan
        run: |
          dotnet sonarscanner begin -d:sonar.coverage.exclusions='**/program.cs' -d:sonar.cs.opencover.reportsPaths='**/coverage.opencover.xml' -d:sonar.host.url='https://sonarcloud.io' -d:sonar.login=${{secrets.SONAR_TOKEN}} -k:'derftx:derftx:dotnet' -o:'derftx'
          dotnet build
          dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:ExcludeByFile='**/program.cs'
          dotnet sonarscanner end -d:sonar.login=${{secrets.SONAR_TOKEN}}
        working-directory: dotnet

  scan_jekyll:
    name: scan_jekyll
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        name: scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=derftx
            -Dsonar.projectKey=derftx:derftx:jekyll
            -Dsonar.sources=.
          projectBaseDir: jekyll

  scan_nodejs:
    defaults:
      run:
        working-directory: nodejs
    name: scan_nodejs
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: configure
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: install
        run: npm clean-install
      - name: test
        run: npm test
      - env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        name: scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.coverage.exclusions=**/*.spec.js
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.organization=derftx
            -Dsonar.projectKey=derftx:derftx:nodejs
            -Dsonar.sources=./src
          projectBaseDir: nodejs

name: inspect

on:
  pull_request:
    branches:
      - main
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
