jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure
        uses: actions/configure-pages@v3
      - name: build
        uses: actions/jekyll-build-pages@v1
        with:
          destination: _site
          source: jekyll
      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

  scan:
    name: scan
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install
        run: |
          npm clean-install
        working-directory: nodejs
      - name: test
        run: |
          npm test
        working-directory: nodejs
      - env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        name: scan_jekyll
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=derftx
            -Dsonar.projectKey=derftx:derftx:jekyll
            -Dsonar.sources=.
          projectBaseDir: jekyll
      - env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        name: scan_nodejs
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.coverage.exclusions=**/*.spec.js,**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.organization=derftx
            -Dsonar.projectKey=derftx:derftx:nodejs
            -Dsonar.sources=./src
          projectBaseDir: nodejs

name: inspect

on:
  pull_request:
    branches:
      - main
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
