jobs:
  build:
    name: build
    uses: fredbelotte/fredbelotte/workflows/jekyll/build.yaml@main
    with:
      jekyll_destination: _site
      jekyll_source: jekyll

  scan:
    name: scan
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install
        run: |
          npm clean-install
        working-directory: nodejs
      - name: test
        run: |
          npm test
        working-directory: nodejs
      - env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        name: scan_jekyll
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=derftx
            -Dsonar.projectKey=derftx:derftx:jekyll
            -Dsonar.sources=.
          projectBaseDir: jekyll
      - env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        name: scan_nodejs
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.coverage.exclusions=main.js,**/*.test.js
            -Dsonar.exclusions=**/*.json
            -Dsonar.organization=derftx
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            -Dsonar.projectKey=derftx:derftx:nodejs
            -Dsonar.sources=.
          projectBaseDir: nodejs

name: inspect

on:
  pull_request:
    branches:
      - main
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
